<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="css/main.css"/>
    <link rel="stylesheet" type="text/css" href="css/nav.css"/>
</head>
<body>
<ul>
    <li><a href="/">Home</a></li>
    <li><a href="fizz-buzz">FizzBuzz</a></li>
    <li><a href="image-uploader">ImageUploader</a></li>
    <li><a href="/">Kontakt</a></li>
</ul>
<?= $templateOutput ?>
</body>
</html>