
<!Doctype html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">
</head>
<body>


<h1>Fizzbuzz Game</h1>

<form id="form" method="get" action="">
    <input id="input" type="text" name="value" placeholder="Zahl oder text eingeben"/> <br/>
    <input id="button" type="submit" name="los" value="Senden"/>
    <link rel="stylesheet" type="text/css" href="../csss/style.css"/>
</form>

<p><?= $htmlVariables['counter'] ?></p> <br/>
<p><?= $htmlVariables['output'] ?></p>

</body>

</html>
