<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="css/main.css"/>
</head>
<body>
    <h1>Choose wich Programm to Start</h1>
    <form action="index.php?side=fizzBuzz" method="POST" enctype="multipart/form-data">
        <input id="button" type="submit" name="submit" value="Fizz Buzz">
    </form>
    <form action="index.php?side=imageUploader" method="POST" enctype="multipart/form-data">
        <input id="button" type="submit" name="submit" value="Image Uploader">
    </form>
</body>
</html>
