
<h1>Image uploader</h1>
<form action="" method="POST" enctype="multipart/form-data">
    <input id="input" type="text" name="title" placeholder="Titel eingeben"><br/><br/><br/>
    <input type="file" name="userFile"><br> <br>
    <input id="button" type="submit" name="upload" value="Hochladen"> <br /><br />
    <?php if(!empty($errorMessage)) : ?>
        <div class="error"><?= $errorMessage?></div>
    <?php endif; ?>
</form>


<?php $blogEntries = []; ?>

<?php foreach($blogEntries as $blogEntry) : ?>
<div>Eintrag: <?= $blogEntry?></div>
<?php endforeach; ?>