<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Title</title>
</head>
<body>
    <form action="index.php?page=fizzBuzz" method="POST" enctype="multipart/form-data">
        <input id="input" type="text" name="title" placeholder="Titel eingeben"><br/><br/><br/>
        <input type="file" name="userFile"><br> <br>
        <input id="button" type="submit" name="upload" value="Hochladen">
    </form>
</body>
</html>
