<!Doctype html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="css/main.css"/>
</head>
<body>
<h1>Fizzbuzz Game</h1>

<form id="form" method="POST" action="">
    <input id="input" type="text" name="value" placeholder="Zahl oder text eingeben"/> <br/>
    <input id="button" type="submit" name="los" value="Senden"/>
</form>



<p><?= $htmlVariables['counter'] ?></p> <br/>
<p><?= $eachSentenceFromOutput[0] ?></p>
<p><?= $eachSentenceFromOutput[1] ?></p>

</body>

</html>
