<div id="artikel">
    <article class="w3-border w3-blue w3-padding"> <?= $output['title'] ?><?= $output['date'] ?></article>
    <article class="w3-border w3-blue w3-padding"><?= $output['text'] ?> </article>
    <article class="w3-border w3-blue w3-padding"><?= $output['author'] ?></article>
</div>

<div id="artikel">
    <label class="titel">1.Kommentarvorhanden :</label>
    <article class="w3-border w3-blue w3-padding"> <?= $comments['name'] ?><label>
            meint:</label><?= $comments['Datum und Uhrzeit'] ?></article>
    <article class="w3-border w3-blue w3-padding"><?= $comments['text'] ?> </article>
</div>

<br/><br/><br/><br/><br/>

<form method="post" class="form-style" >
    <fieldset>
        <legend class="titel">Kommentarschreiben :</legend>
        <p>
            <label class="form-label-style" >Name :</label>
            <input  type="text" value=""/>
        </p>
        <p>
            <label class="form-label-style">Mail (optional) :</label>
            <input type="text" name="plz" value=""/>
        </p>
        <p>
            <label class="form-label-style" for="plz">URL (optional) :</label>
            <input type="text" name="plz" value=""/>
        </p>
        <p>
            <label class="form-label-style" >Bemerkung :</label>
            <textarea rows="4" cols="25" placeholder="Bemerkungen!!"></textarea>
        </p>
    </fieldset>
    <input class="w3-button only-send-btn" type="Submit" name="newComments" value="Absenden" />
</form>