<form  class="form-style">
    <p>
        <label class="form-label-style" >Date</label>
        <input  type="date" value="<?= date("d.m.Y")?>" />
    </p>
    <p>
        <label class="form-label-style">Titel</label>
        <input type="text" name="plz" value=""/>
    </p>

    <p>
        <label class="form-label-style" >Text :</label>
        <textarea rows="15" cols="35" placeholder="Textschreiben"></textarea>
    </p>
    <p>
        <input class="w3-button only-send-btn" type="submit" name="" value="Absenden" />
    </p>
</form>

