<?php foreach ($blogEntries as $blogEntry) : ?>
    <div id="artikel">
        <article class="w3-border w3-blue w3-padding"><p>
                <?php if (date('d.m.Y') === $blogEntry['date']): ?>
                    <?= $blogEntry['date'] = 'Heute :' ?>
                <?php else: ?>
                    <?= $blogEntry['date'] ?>
                <?php endif; ?>
                <?= $blogEntry['titel'] ?> </p>
        </article>
        <article class="w3-border w3-blue w3-padding">
            <?php
            $content = strlen($blogEntry['content']);
            if ($content >= 1000) :?>
                <?= substr($blogEntry['content'], 0, 1000) ?>

                <form method="post" action="detail"><label>...[<input type="submit"name="Weiterlesen" value="Weiterlesen"/>  ]</label></form>
            <?php else: ?>
                <?= $blogEntry['text'] ?>
            <?php endif; ?>
        </article>

        <article class="w3-border w3-blue w3-padding"><p>Author: <?= $blogEntry['author'] ?></p></article>
    </div>
<?php endforeach; ?>